version: "3.5"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mongo:
    image: mongo
    command: --smallfiles
    container_name: mongo
    ports:
      - 27017:27017
  service-discovery:
    image: msarthak/service-discovery
    container_name: service-discovery
    ports:
      - 8761:8761
  asset:
    image: msarthak/asset-service
    container_name: asset
    ports:
      - 8081:8081
    depends_on:
      - service-discovery
      - mongo
      - kafka
  asset-rental-deal:
    image: msarthak/asset-rental-deal-service
    container_name: asset-rental-deal
    ports:
      - 8080:8080
    depends_on:
      - asset
      - service-discovery
      - mongo
      - kafka